### ISSUE TITLE
tuf-on-ci migration preparation

### ISSUE THREAD

**Issue by jku** [sigstore/root-signing#1247]
In preparation for #929, we should do all preparing steps that are not limited by the online signing schedule and that will not affect the current day-to-day operation of this repository.

Checklist of things to do before the signing event

* [ ] Decide/ communicate  signing event date (currently looking at week 35-36, we'll make a proposal in next days)
* [x] decide/communicate sigstore-rs situation (#1251): @kommendorkapten assigned
* [x] tuf-on-ci work
   * [x] Finish support for external delegations (https://github.com/theupdateframework/tuf-on-ci/pull/384): @kommendorkapten assigned
   * [x] Possibly include a solution to scheduling issue WRT legacy online signing during the signing event: @jku assigned (https://github.com/theupdateframework/tuf-on-ci/pull/395): this would remove the very tight deadline from the signing event
     * based on current review this will actually work even if legacy online signing happens: the import signing event does not modify the online roles so the merge will be clean
   * [x] Release tuf-on-ci 0.12 with needed features
   * [x] Deploy the release on root-signing-staging 
* [x] Initial review of workflow changes for signing event #1313  (we should merge this as part of signing event but can review already)
* [x] #1261
* [x] terraform changes 
   * [x] #1314: @jku assigned
   * [x] https://github.com/sigstore/community/pull/451
* [x] Update `targets/` so its content match the expected repository artifacts
* [x] Add scripts/data needed for the migration
* [x] Add the new workflows (in a disabled state at this point)
* [x] Add a playbook for the migration
* [x] Add new playbook(s) for signers

**Comment by jku** [comment]
https://github.com/jku/root-signing/pull/1 contains the workflow enabling/disabling commits that we should include in the initial signing event branch (to disable legacy workflows and enable tuf-on-ci ones)

**Comment by jku** [comment]
Collecting items that must be done before initial tuf-on-ci signing event

* [ ] Decide/ communicate  signing event date (currently looking at week 35-36, we'll make a proposal in next days)
* [ ] decide/communicate sigstore-rs situation (#1251): @kommendorkapten assigned
* [ ] Release tuf-on-ci with needed features
   * [ ] Finish support for external delegations (https://github.com/theupdateframework/tuf-on-ci/pull/384): @kommendorkapten assigned
   * [ ] Possibly include a solution to scheduling issue WRT legacy online signing during the signing event: @jku assigned (https://github.com/theupdateframework/tuf-on-ci/pull/395): this would remove the very tight deadline from the signing event
* [ ] Initial review of workflow changes for signing event #1313 
* [ ] #1261
* [ ] terraform changes 
   * [ ] #1314 
   * [x] https://github.com/sigstore/community/pull/451

**Comment by jku** [comment]
FYI @haydentherapper

**Comment by jku** [comment]
marking this closed: the actual migration is in #1320
